name: jasa_go
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

